### PR TITLE
Fix warnings in RobotContainer & Fix local dependencies

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ethan-ss-nyder** [comment]
There's some merge conflicts, bucko.

**Comment by ghost** [comment]
I've fixed the merge conflicts as well as fixed some Gradle build files

**Comment by ghost** [comment]
Just in time for Kettering: I *finally* figured out how to pull our home-grown dependencies in a single build

**Comment by ghost** [comment]
I'm gonna go ahead and merge this because these are really much needed changes.

**Pull request merged**
